// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is the interface satisfied by both *pgx.Conn and *pgxpool.Pool.
// This makes the generated queries usable with either a single connection or a pool.
type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

// New creates a new Queries instance backed by the provided DBTX.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Queries holds the database connection and all prepared query methods.
type Queries struct {
	db DBTX
}

// WithTx returns a new Queries instance that uses the provided transaction.
// Useful when you need multiple operations in a single atomic transaction.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
