// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
	"time"
)

// ── Query strings ─────────────────────────────────────────────────────────────

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, dob)
VALUES ($1, $2)
RETURNING id, name, dob
`

const getUser = `-- name: GetUser :one
SELECT id, name, dob
FROM users
WHERE id = $1
`

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1,
    dob  = $2
WHERE id = $3
RETURNING id, name, dob
`

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob
FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

// ── Parameters structs ────────────────────────────────────────────────────────

// CreateUserParams holds the input for inserting a new user.
type CreateUserParams struct {
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
}

// UpdateUserParams holds the input for updating an existing user.
type UpdateUserParams struct {
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
	ID   int32     `json:"id"`
}

// ListUsersParams holds pagination parameters.
type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ── Query methods ─────────────────────────────────────────────────────────────

// CreateUser inserts a new user and returns the created row.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Dob)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

// GetUser fetches a single user by primary key.
func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

// UpdateUser updates name and dob for an existing user and returns the row.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.Dob, arg.ID)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

// DeleteUser removes a user by ID. Returns no rows.
func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

// ListUsers returns a paginated list of users ordered by ID.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return users, nil
}

// CountUsers returns the total number of users (used for pagination metadata).
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
